# Generated by Django 4.2.10 on 2025-05-10 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="code"),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="montant de réduction",
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="pourcentage de réduction"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="valide à partir de")),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="valide jusqu'à"
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="utilisations maximum"
                    ),
                ),
                (
                    "current_uses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="utilisations actuelles"
                    ),
                ),
                (
                    "is_single_use",
                    models.BooleanField(
                        default=False, verbose_name="usage unique par utilisateur"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="coupons",
                        to="courses.course",
                        verbose_name="cours applicables",
                    ),
                ),
            ],
            options={
                "verbose_name": "coupon",
                "verbose_name_plural": "coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="devise"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("completed", "Complété"),
                            ("failed", "Échoué"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="méthode de paiement"
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="ID de paiement"
                    ),
                ),
                (
                    "charge_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID de transaction"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de mise à jour"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="métadonnées"
                    ),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="courses.enrollment",
                        verbose_name="inscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "paiement",
                "verbose_name_plural": "paiements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="numéro de facture"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/",
                        verbose_name="fichier PDF",
                    ),
                ),
                (
                    "billing_name",
                    models.CharField(max_length=255, verbose_name="nom de facturation"),
                ),
                (
                    "billing_address",
                    models.TextField(blank=True, verbose_name="adresse de facturation"),
                ),
                (
                    "billing_city",
                    models.CharField(blank=True, max_length=100, verbose_name="ville"),
                ),
                (
                    "billing_country",
                    models.CharField(blank=True, max_length=100, verbose_name="pays"),
                ),
                (
                    "billing_postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="code postal"
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="payments.payment",
                        verbose_name="paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "facture",
                "verbose_name_plural": "factures",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date d'utilisation"
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="payments.coupon",
                        verbose_name="coupon",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_usage",
                        to="payments.payment",
                        verbose_name="paiement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_usages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "utilisation de coupon",
                "verbose_name_plural": "utilisations de coupons",
                "ordering": ["-used_at"],
                "unique_together": {("coupon", "user", "payment")},
            },
        ),
    ]
