# Generated by Django 4.2.10 on 2025-05-10 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="city",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="country",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_instructor",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_student",
        ),
        migrations.AddField(
            model_name="customuser",
            name="account_verified",
            field=models.BooleanField(default=False, verbose_name="compte vérifié"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_notifications",
            field=models.BooleanField(
                default=True, verbose_name="notifications par email"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="expertise",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="domaine d'expertise"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="facebook",
            field=models.URLField(blank=True, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="instagram",
            field=models.URLField(blank=True, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(default="fr", max_length=10, verbose_name="langue"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP de dernière connexion"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="linkedin",
            field=models.URLField(blank=True, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="twitter",
            field=models.URLField(blank=True, verbose_name="Twitter"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("student", "Étudiant"),
                    ("instructor", "Instructeur"),
                    ("admin", "Administrateur"),
                ],
                default="student",
                max_length=20,
                verbose_name="type d'utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, verbose_name="adresse"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="numéro de téléphone"
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_goal",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="objectif d'apprentissage",
                    ),
                ),
                (
                    "learning_style",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="style d'apprentissage"
                    ),
                ),
                (
                    "daily_goal_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="objectif quotidien (minutes)"
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True, default=list, verbose_name="compétences"
                    ),
                ),
                (
                    "interests",
                    models.JSONField(
                        blank=True, default=list, verbose_name="centres d'intérêt"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="titre professionnel"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="entreprise"
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="secteur d'activité"
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="niveau d'éducation"
                    ),
                ),
                (
                    "certificates",
                    models.JSONField(
                        blank=True, default=list, verbose_name="certificats"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil utilisateur",
                "verbose_name_plural": "profils utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="titre")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="lu")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("general", "Général"),
                            ("course", "Cours"),
                            ("assignment", "Devoir"),
                            ("system", "Système"),
                            ("payment", "Paiement"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="type de notification",
                    ),
                ),
                ("link", models.URLField(blank=True, verbose_name="lien")),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="courses.course",
                        verbose_name="cours",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
