# Generated by Django 4.2.10 on 2025-05-15 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="billing_postal_code",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="charge_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="enrollment",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_id",
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_postcode",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="code postal de facturation"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="montant de la réduction",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="pourcentage de réduction",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="sous-total"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="montant de la taxe",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="pourcentage de taxe",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="total"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="courses.course",
                verbose_name="cours",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date de paiement"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_details",
            field=models.TextField(blank=True, verbose_name="détails du paiement"),
        ),
        migrations.AddField(
            model_name="payment",
            name="reference_id",
            field=models.CharField(
                blank=True, max_length=100, unique=True, verbose_name="ID de référence"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ID de paiement Stripe"
            ),
        ),
        migrations.AlterField(
            model_name="couponusage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_usages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="billing_city",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ville de facturation"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="billing_country",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="pays de facturation"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="billing_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="nom de facturation"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="numéro de facture"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Carte de crédit"),
                    ("paypal", "PayPal"),
                    ("bank_transfer", "Virement bancaire"),
                ],
                default="card",
                max_length=20,
                verbose_name="méthode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("completed", "Complété"),
                    ("failed", "Échoué"),
                    ("refunded", "Remboursé"),
                    ("disputed", "Contesté"),
                    ("canceled", "Annulé"),
                ],
                default="pending",
                max_length=20,
                verbose_name="statut",
            ),
        ),
    ]
