name: CI/CD Django → PythonAnywhere
on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: eduplus-dev

    steps:
      # 1. Récupération du code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Installation des dépendances système
      - name: Install system deps (Cairo, pkg-config…)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2-dev \
            pkg-config \
            python3-dev

      # 3. Préparation de Python  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4. Installation des requirements  
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Exécution des tests Django  
      - name: Run Django tests
        run: python manage.py test --verbosity=2

      # 6. Déclenchement du déploiement PythonAnywhere  
      - name: Trigger PythonAnywhere deploy
        env:
          PA_USER: ${{ secrets.PA_USER }}
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
        run: |
          curl -X POST \
            "https://www.pythonanywhere.com/api/v0/user/${PA_USER}/webhooks/github/?token=${PA_TOKEN}"
