name: CI/CD Django → PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupère le code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Installe Python et dépendances
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Lancer les tests
      - name: Run Django tests
        run: |
          python manage.py test --verbosity=2

      # 4. Déployer via webhook PythonAnywhere
      - name: Trigger PythonAnywhere deploy
        env:
          PA_USER: ${{ secrets.PA_USER }}
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
        run: |
          curl -X POST \
            "https://www.pythonanywhere.com/api/v0/user/${PA_USER}/webhooks/github/?token=${PA_TOKEN}"
