name: CI/CD Django → PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: eduplus-dev

    steps:
      # 1. Checkout du code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Installation des dépendances système
      - name: Install system deps (Cairo, pkg-config…)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2-dev \
            pkg-config \
            python3-dev

      # 3. Setup de Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4. Installation des requirements
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Lancer les tests Django
      - name: Run Django tests
        run: |
          python manage.py test --verbosity=2

      # 6. Reload de la webapp PythonAnywhere
      - name: Reload PythonAnywhere webapp
        env:
          PA_USER:   ${{ secrets.PA_USER }}
          PA_TOKEN:  ${{ secrets.PA_TOKEN }}
          PA_DOMAIN: amenyayedi.pythonanywhere.com
        run: |
          curl -X POST \
            -H "Authorization: Token ${PA_TOKEN}" \
            "https://www.pythonanywhere.com/api/v0/user/${PA_USER}/webapps/${PA_DOMAIN}/reload/"
