# fichier : .github/workflows/deploy-to-pythonanywhere.yml
name: CI/CD Django → PythonAnywhere

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: eduplus-dev

    steps:
      # 1) Récupérer le code
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Installer Python et vos déps
      - name: Setup Python & install requirements
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          # forcer reportlab compatible xhtml2pdf
          pip install reportlab==3.6.12
          pip install -r requirements.txt

      # 3) Déployer sur PythonAnywhere
      - name: Deploy & migrate & collectstatic & reload
        uses: umuttopalak/pythonanywhere-deploy-action@v1.1.2
        with:
          host:        'www.pythonanywhere.com'
          username:    ${{ secrets.PA_USER }}
          api_token:   ${{ secrets.PA_TOKEN }}
          domain_name: ${{ secrets.PA_DOMAIN }}
