# .github/workflows/deploy-to-pythonanywhere.yml
name: CI/CD Django → PythonAnywhere

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: eduplus-dev

    steps:
      # 1) Checkout du code
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Installer les libs système pour pycairo
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev pkg-config python3-dev

      # 3) Setup Python + pip install local pour valider la build
      - name: Setup Python & install requirements locally
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install reportlab==3.6.12    # lock ReportLab compatible
          pip install -r requirements.txt

      # 4) Déployer sur PythonAnywhere
      - name: Deploy → PythonAnywhere (migrate, collectstatic, reload)
        uses: umuttopalak/pythonanywhere-deploy-action@v1.1.2
        with:
          host:        'www.pythonanywhere.com'
          username:    ${{ secrets.PA_USER }}
          api_token:   ${{ secrets.PA_TOKEN }}
          domain_name: ${{ secrets.PA_DOMAIN }}
